misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    font_family = Monospace
}

cursor {
    no_hardware_cursors = true
}

general {
    border_size = 0
    gaps_in = 0
    gaps_out = 0
}

decoration {
    rounding = 0
    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

input {
    kb_layout = us
}

exec-once = hyprlogin
